# Generated by Django 5.0.2 on 2024-04-08 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file',
            new_name='files',
        ),
    ]
