# Generated by Django 4.2.13 on 2024-05-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0002_folder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='uid',
            field=models.UUIDField(default='df0fe254ae9f400fb043de7341de057c', editable=False, primary_key=True, serialize=False),
        ),
    ]
