# Generated by Django 5.0.2 on 2024-04-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0002_rename_file_files_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='files',
            new_name='file',
        ),
    ]
