# Generated by Django 4.2.13 on 2024-05-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0005_signedurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedurl',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shareapp.folder'),
        ),
    ]
