# Generated by Django 4.2.11 on 2024-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0007_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(choices=[('room1', 'General Inquiry'), ('room2', 'Technical Support'), ('room3', 'Security Concerns'), ('room4', 'Other')], max_length=50),
        ),
    ]
