# Generated by Django 4.2.11 on 2024-06-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0008_alter_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(choices=[('room1-GI', 'General Inquiry'), ('room2-TS', 'Technical Support'), ('room3-SC', 'Security Concerns'), ('room4-OTH', 'Other')], max_length=50),
        ),
    ]
